name: Java CI with Maven

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17

    # from https://github.com/marketplace/actions/cache
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    # from https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
    - name: Build and Test with Maven
      id: buildandtest
      timeout-minutes: 15
      run: ./mvnw -B test
      
    # PPAC37 trying to create an issue if the ci test faild and a specifc file have been created   
    # https://github.com/peter-evans/create-issue-from-file used in https://github.com/lycheeverse/lychee-action
    # https://github.com/marketplace/actions/create-issue-from-file
    - name: Create Issue From File
      if: ${{ steps.buildandtest.outputs.exit_code == 0 }}
      uses: peter-evans/create-issue-from-file@v3
      with:
        title: Language Missing Key Checker Report
        content-filepath: missing_language.md
        labels: report, automated issue
        #issue-number: 

    - name: Package with Maven
      run: ./mvnw -B clean package -DskipTests

    - name: Prepare package for release
      run: mv ./target/Makelangelo-*-with-dependencies.jar ./target/to-upload.jar

    - name: Upload artifact for release
      uses: actions/upload-artifact@v2
      with:
        name: artifact
        path: target/to-upload.jar
        retention-days: 5

  # from https://docs.github.com/en/actions/advanced-guides/storing-workflow-data-as-artifacts
  deploy-nightly:
    runs-on: windows-latest
    needs: build
    if: github.repository == 'MarginallyClever/Makelangelo-software' && github.ref == 'refs/heads/master'
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: artifact

      # from https://github.com/marketplace/actions/deploy-nightly
    - name: Deploy universal release
      uses: WebFreak001/deploy-nightly@v1.1.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # automatically provided by github actions
      with:
        # find out this value by opening https://api.github.com/repos/<owner>/<repo>/releases
        # in your browser and copy the full "upload_url" value including the {?name,label} part
        upload_url: https://uploads.github.com/repos/MarginallyClever/Makelangelo-software/releases/54908875/assets{?name,label}
        release_id: 54908875 # same as above (id can just be taken out the upload_url, it's used to find old releases)
        asset_path: to-upload.jar # path to archive to upload
        asset_name: makelangelo-nightly-$$.jar # name to upload the release as, use $$ to insert date (YYYYMMDD) and 6 letter commit hash
        asset_content_type: application/zip # required by GitHub API
        max_releases: 3 # optional, if there are more releases than this matching the asset_name, the oldest ones are going to be deleted
